# Generated by Django 4.1.7 on 2023-02-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB')], default=0, max_length=16),
            preserve_default=False,
        ),
    ]
